---
title: Ferdi Şahin
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ferdisahin@hotmail.it
description: Web Tasarımcı'nın Defteri
baseurl: ''
url: http://www.frdshn.com
videoarea: false
disqus: 
owner:
  name: Ferdi Şahin
  avatar: avatar.jpg
  facebook: 100012658995912
  twitter: 
  instagram: 
  about: Merhaba, benim adım Ferdi. Blogumda yararlı bilgileri bulabilirsiniz. Kısaca
    Front End / Wordpress geliştiricisi sayılırım. Son zamanlarda ise Jekyll'a ilgi
    duymaya başladım. :)
twitter:
  username: 
logo: 
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
gems:
- jekyll-paginate
- jekyll-seo-tag
paginate: 5
permalink: "/:categories/:title.html"
markdown: kramdown
inclue:
- ".htaccess"
exclude:
- Gemfile
- Gemfile.lock
theme: jekyll-theme-cayman
